[[constraint]]
  name = "github.com/PuerkitoBio/goquery"
  version = "1.1.0"

[[constraint]]
  name = "github.com/google/go-querystring"
  branch = "master"

[[constraint]]
  name = "github.com/gosuri/uilive"
  branch = "master"

[[constraint]]
  name = "github.com/olekukonko/tablewriter"
  branch = "master"

[[constraint]]
  name = "github.com/onsi/ginkgo"
  version = "1.4.0"

[[constraint]]
  name = "github.com/onsi/gomega"
  version = "1.2.0"

[[constraint]]
  name = "github.com/pivotal-cf/jhanda"
  branch = "master"

[[constraint]]
  name = "golang.org/x/oauth2"
  branch = "master"

[[constraint]]
  name = "gopkg.in/yaml.v2"
  branch = "v2"

[[constraint]]
  name = "github.com/ghodss/yaml"
  version = "1.0.0"
